[workspace]
resolver = "3"
members = [
    "kernel",
    "rt",
    "shared_consts",
    "userspace/init",
    "userspace/cli",
    "userspace/ls", 
    "userspace/shutdown", "userspace/touch", "userspace/cat", "userspace/reboot",
]
default-members = ["kernel"]
exclude = [
    "bootloader",
]

[profile.release]
opt-level = 2
strip = "symbols"
# debug = 2
# strip = "none"

overflow-checks = true
lto = "fat"
panic = "abort"

# TODO : change this ?
[profile.release.package.bootloader]
debug = true
