use std::{env, fs, path::{Path, PathBuf}, process::Command};

fn write_empty_symbols(out_file : &Path){
    fs::write(out_file, "// generated by build.rs\npub static KERNEL_SYMBOLS: &[KernelSymbol] = &[];\n").unwrap();
}

fn escape_rust_string(name: &str) -> String {
    name.replace('\\', "\\\\").replace('"', " \\\"")
}

fn unmangle_symbol(name : &str) -> Result<String, String> {
    let output = Command::new("rustfilt").arg(name).output().map_err(|e| format!("failed to run rustfilt: {e}"))?;
    if !output.status.success(){
        return Err(format!("rustfilt failed with status {:?}: {}", output.status.code(), String::from_utf8_lossy(&output.stderr)));
    }

    let output_text = String::from_utf8_lossy(&output.stdout).trim_end_matches('\n').to_owned();
    Ok(output_text)
}

fn generate_symbols(kernel_elf: &Path) -> Result<String, String> {
    let output = Command::new("nm").arg("-n").arg(kernel_elf).output().map_err(|e| format!("failed to run nm: {e}"))?;
    if !output.status.success(){
        return Err(format!("nm failed with status {:?}: {}", output.status.code(), String::from_utf8_lossy(&output.stderr)));
    }

    let nm_text = String::from_utf8_lossy(&output.stdout);

    let mut generated = String::new();
    generated.push_str("// generated by build.rs; do not edit manually\n");
    generated.push_str("pub static KERNEL_SYMBOLS: &[KernelSymbol] = &[\n");

    for line in nm_text.lines(){
        let parts = line.split_whitespace().collect::<Vec<_>>();
        if parts.len() < 3 {
            continue;
        }

        let addr = parts[0];
        let kind = parts[1];

        let name = parts[2..].join(" ");

        if kind != "T" && kind != "t" && kind != "W" && kind != "w" {
            continue;
        }

        if usize::from_str_radix(addr, 16).is_err(){
            continue;
        }
        if name.starts_with(".L") || name.starts_with("$"){
            continue;
        }

        let unmangled_name = unmangle_symbol(&name)?;

        let escaped = escape_rust_string(&unmangled_name);

        generated.push_str(&format!("    KernelSymbol {{ addr: 0x{}usize, name: \"{}\" }},\n", addr, escaped));
    }

    generated.push_str("];\n");

    Ok(generated)
    
}

fn generate_symbol_table(target_dir : &Path, profile : &str){
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let kernel_elf = PathBuf::from_iter([ target_dir, "x86_64-unknown-kernel".as_ref(), profile.as_ref(), "rust-kernel".as_ref() ]);

    let out_file = PathBuf::from_iter([ out_dir.as_path(), "generated_symbols.rs".as_ref() ]);

    if !kernel_elf.exists(){
        write_empty_symbols(&out_file);
        return;
    }

    match generate_symbols(&kernel_elf){
        Ok(generated) => {
            fs::write(&out_file, generated).unwrap();
        }
        Err(err) => {
            eprintln!("warning: failed to generate kernel symbols: {err}");
            write_empty_symbols(&out_file);
        }
    }
}

fn find_target_dir() -> PathBuf {
    if let Ok(target_dir) = env::var("CARGO_TARGET_DIR") {
        return PathBuf::from(target_dir);
    }
    PathBuf::from("../target")
}

fn add_exe_to_initrd(target_dir : &Path, profile : &str, exe : &str){
    let bin = PathBuf::from_iter([ target_dir, "x86_64-unknown-rust_kernel".as_ref(), profile.as_ref(), exe.as_ref() ]);

    println!("cargo:rerun-if-changed={}", bin.display());

    dbg!(bin.display());
    let to_path = format!("../initrd/{exe}");
    fs::copy(&bin, to_path).expect("failed to copy executable");
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-link-arg=-Tkernel/linker.ld");
    println!("cargo:rerun-if-changed=../initrd");

    let profile = env::var("PROFILE").unwrap();

    let target_dir = find_target_dir();

    add_exe_to_initrd(&target_dir, &profile, "init");
    add_exe_to_initrd(&target_dir, &profile, "cli");
    add_exe_to_initrd(&target_dir, &profile, "ls");
    add_exe_to_initrd(&target_dir, &profile, "shutdown");
    

    let _ = Command::new("tar")
        .args([
            "-C",
            "../initrd",
            "-cf",
            "initrd.tar",
            ".",
        ])
        .status()
        .expect("failed to execute tar");

    generate_symbol_table(&target_dir, &profile);
}