[package]
name = "bootloader"
version = "0.9.35"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental pure-Rust x86 bootloader."
repository = "https://github.com/rust-osdev/bootloader"
edition = "2018"
build = "build.rs"

[[bin]]
name = "bootloader"
path = "bios/main.rs"
required-features = ["binary"]

[[bin]]
name = "bootloader-uefi"
path = "uefi/main.rs"
required-features = ["binary", "uefi"]

[lib]
test = false
bench = false


[dependencies]
cfg-if = "1.0.4"
x86_64 = { version = "0.15.5", optional = true, default-features = false, features = ["instructions"] }
usize_conversions = { version = "0.2.0", optional = true }
bit_field = { version = "0.10.0", optional = true }
raw-cpuid = { version = "11.6.0", optional = true }
uefi = { version = "0.39", optional = true }
spin = { version = "0.12.0", optional = true }
rsdp = { version = "2.0.1", optional = true }
arrayvec = { version = "0.7.6", default-features = false, optional = true  }
elf = { version = "0.8.0", default-features = false, features = ["to_str"], optional = true } # TODO : try to remove the to_str feature ?

[dependencies.font8x8]
version = "0.3.1"
default-features = false
features = ["unicode"]
optional = true

[build-dependencies]
llvm-tools = { version = "0.1", optional = true }
toml = { version = "0.5.1", optional = true }

[features]
default = []
binary = ["elf", "x86_64", "usize_conversions", "llvm-tools", "toml", "raw-cpuid", "spin", "rsdp", "arrayvec"]
vga_320x200 = ["font8x8"]
recursive_page_table = []
map_physical_memory = []
sse = ["bit_field"]
uefi = [ "dep:uefi", "font8x8" ]

[package.metadata.bootloader]
target = "x86_64-bootloader.json"
build-std = "core"

[package.metadata.docs.rs]
features = [ "recursive_page_table", "map_physical_memory" ]
default-target = "x86_64-unknown-linux-gnu"

[profile.release]
debug = 2
strip = "none"
